name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest
      options: --user root
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install dependencies
        run: shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Run tests
        run: crystal spec
